DROP TABLE IF EXISTS owner CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS pizzas CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders;


CREATE TABLE owner (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE customers (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
phone INTEGER NOT NULL
);

CREATE TABLE pizzas (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(250),
topping VARCHAR(255),
price VARCHAR(255) NOT NULL,
pizza_time INTEGER NOT NULL,
picture VARCHAR(255) NOT NULL
);


CREATE TABLE orders (
   id SERIAL PRIMARY KEY NOT NULL,
   customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
   total_price VARCHAR(255) NOT NULL,
   order_date DATE,
   ordering_time TIME,
   pick_up_time TIME
);

CREATE TABLE order_items (
id SERIAL PRIMARY KEY NOT NULL,
item_price VARCHAR(255) NOT NULL,
size VARCHAR (250),
pizza_id INTEGER REFERENCES pizzas(id) ON DELETE CASCADE,
order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
quantity INTEGER
);



